"project_id": "93623"
"api_token": "f8008312cf9e7e8a2d17f00db307c5a1"

"files": [
  {
    "source": "/src/assets/languages/*.json",
    "translation": "/src/assets/languages/%two_letters_code%.json"
  }
]